include: package:very_good_analysis/analysis_options.yaml
# https://dartcodemetrics.dev/docs/

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false

analyzer:
  exclude:
    # Generated code
    - '**.g.dart'
    - '**.freezed.dart'
    - 'lib/**.graphql.dart'
    - 'lib/**.gen.dart'
    - 'lib/generated_plugin_registrant.dart'
    - 'lib/pigeon.dart'
    # Firebase
    - 'lib/firebase_options.dart'
    # Localization
    - 'lib/src/common/localization/intl/**'
    - 'lib/src/common/localization/l10n.dart'
    # Tests
    - 'test/**.mocks.dart'
    - '.test_coverage.dart'
    # Web
    - 'web/**'
    # Build
    - 'build/**'
    # Assets
    - 'assets/**'


  plugins:
    - dart_code_metrics
# >>>>>>>>>dart_code_metrics
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    # цикломатическая сложность
    # количество вложенных структур,
    # условных операторов,
    # операторов ветвления
    # стартовая сложность 1
    cyclomatic-complexity: 20
    # количество вложенных ветвлений
    maximum-nesting-level: 5
    # количество параметров в функции
    number-of-parameters: 6
    # длина тела функции в строчках
    source-lines-of-code: 100
    # объём операций и операндов
    # количество информации для понимания \ анализа
    halstead-volume: 150
    # длина функции в строчках
    lines-of-code: 150
    # индекс поддержки
    # определяем насколько поддреживаема функция
    # и насколько изменяема
    # зависит от некоторых параметров выше
    # (сложность, объём, количетсво строчек)
    maintainability-index: 50
    # количество методов в классе
    number-of-methods: 10
  metrics-exclude:
    - test/**
    - ios/**
    - android/**
  rules-exclude:
    - lib/firebase_options.dart
  rules:
    # common
    - avoid-collection-methods-with-unrelated-types
    - avoid-duplicate-exports
    - avoid-dynamic
    - avoid-global-state
    - avoid-ignoring-return-values
    - avoid-missing-enum-constant-in-map
    #        - avoid-nested-conditional-expressions:
    #              acceptable-level: 3
    # ???
    #        - avoid-passing-async-when-sync-expected
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - member-ordering:
        alphabetize: false
        order:
          - fields
          - constructors
          - getters-setters
          - private-methods
          - public-methods
        widgets-order:
          - fields
          - constructors
          - getters-setters
          - init-state-method
          - private-methods
          - overridden-public-methods
          - dispose-method
          - build-method
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-magic-number
    - no-object-declaration
    - prefer-async-await
    - prefer-conditional-expressions
    - prefer-correct-identifier-length:
        exceptions: [ 'i' ]
        min-identifier-length: 2
        max-identifier-length: 30
    # flutter
    - prefer-first
    - prefer-last
    - binary-expression-operand-order
    - double-literal-format
    - prefer-const-border-radius
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-match-file-name
    - prefer-moving-to-variable
    - prefer-trailing-comma
    # Flutter specific
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    # ???
    #        - avoid-shrink-wrap-in-lists
    - avoid-unnecessary-setstate
    - avoid-use-expanded-as-spacer
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - onPressed
          - onTap
        allowed-line-count: 6
