/// Flutter icons Itmo_logo
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Itmo_logo
///      fonts:
///       - asset: fonts/Itmo_logo.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ItmoLogo {
  ItmoLogo._();

  static const _kFontFam = 'Itmo_logo';

  static const IconData itmo = IconData(
    0xe800,
    fontFamily: _kFontFam,
  );
  static const IconData itmoText = IconData(
    0xe801,
    fontFamily: _kFontFam,
  );
}
